name: 'Get Output URL'
description: 'Generate Job URLs'
author: 'Rob Nutland'
inputs:
  APP_ID:
    description: Numeric identifier of the GitHub App with permissions to execute the required repository workflow.
  APP_PRIVATEKEY:
    description: The private key of the GitHub app.
  INSTALLATION_ID:
    description: Uniquely identifies a specific installation of the GitHub app to a repository. 
  OWNER:
    description: Owner of the repo containing the workflow.
  REPO:
    description: Repo containing the workflow.
  WORKFLOW_ID:
    description: Workflow name or numerical identifier.
  REF:
    description: Tag or branch of the repo that the workflow should execute on.
  INPUTS:
    description: The inputs that are to be passed to the workflow.
  JOB_INDEX:
    description: The index number of the workflow's job that a log URL should be returned for.
outputs:
  url:
    description: 'URL to the log of the specified workflow job.'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'lock'
  color: 'yellow'
